# Generated by Django 4.0.4 on 2022-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto_trainee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moduleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=150)),
                ('module_name', models.CharField(max_length=150)),
                ('module_description', models.CharField(max_length=950)),
                ('module_imageUrl', models.URLField(max_length=250)),
                ('module_demoUrl', models.URLField(max_length=250)),
                ('module_text', models.CharField(max_length=1950)),
                ('module_sampleUrl', models.URLField(max_length=250)),
            ],
        ),
    ]
